apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-deployment
  namespace: flows-docs
  labels:
    app: docs
spec:
  replicas: $EKS_DOCS_REPLICAS
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
      - name: docs
        image: $EKS_DOCS_IMAGE:$EKS_DOCS_IMAGE_TAG
        ports:
        - containerPort: 3000

